# Generated by Django 4.1 on 2023-12-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_client_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cell_phone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
